apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-postgres-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ext-postgres-operator
  template:
    metadata:
      labels:
        name: ext-postgres-operator
    spec:
      serviceAccountName: ext-postgres-operator
      containers:
        - name: ext-postgres-operator
          image: movetokube/postgres-operator:0.2
          command:
          - postgres-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ext-postgres-operator"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: ext-postgres-operator
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ext-postgres-operator
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: ext-postgres-operator
                  key: POSTGRES_PASS
            - name: POSTGRES_URI_ARGS
              valueFrom:
                secretKeyRef:
                  name: ext-postgres-operator
                  key: POSTGRES_URI_ARGS