apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
        - name: postgres-operator
          # Replace this with the built image name
          image: movetokube/postgres-operator:0.2
          command:
          - postgres-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ext-postgres-operator"
            - name: POSTGRES_HOST
              value: <your PostgreSQL server host>
            - name: POSTGRES_USER
              value: <your postgresql admin user>
            - name: POSTGRES_PASS
              value: <your postgresql admin password>
            - name: POSTGRES_URI_ARGS
              value: <Any args to URI, empty string if none>
