apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
        - name: postgres-operator
          # Replace this with the built image name
          image: hitman99/postgres-operator:0.1
          command:
          - postgres-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "postgres-operator"
            - name: POSTGRES_URL
              value: "postgresql://postgres:admin123@postgres:5432?sslmode=disable"
            - name: POSTGRES_HOST
              value: "postgres:5432"
