kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-operator
subjects:
- kind: ServiceAccount
  name: postgres-operator
  namespace: operators
roleRef:
  kind: ClusterRole
  name: postgres-operator
  apiGroup: rbac.authorization.k8s.io
