apiVersion:v1
kind: Secret
  metadata:
  name: aws-service-operator-config
  namespace: <NAMESPACE>
type: Opaque
stringData:
  CLUSTER_NAME: "<CLUSTER_NAME>"
  REGION: "<REGION>"
  ACCOUNT_ID: "<000000000000>"