apiVersion: v1
kind: Secret
  metadata:
  name: postgres-operator
  namespace: operators
type: Opaque
stringData:
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASS: admin
  POSTGRES_URI_ARGS: